FROM alpine:3.18 as builder

RUN apk add --no-cache python3-dev py3-pip && pip3 install --upgrade pip

WORKDIR /devops-app

COPY . /devops-app

RUN pip3 --no-cache-dir install -r requirements.txt

# Copie los archivos de la imagen de compilación a la imagen de producción
FROM alpine:3.18 as production

COPY --from=builder /devops-app /devops-app

# Establezca el comando de entrada para la imagen de producción
CMD ["python3", "src/routes.py"]