# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application TP Devops

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test unit tests
      run: python -m unittest discover -s src -p 'test_app.py'

  push_to_docker_hub_registry:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    needs: build_and_test
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Log in to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USER }}
      
      - name: Build and tag Docker image
        run: docker compose up -d

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/devops-tp-devops-app:${{ github.sha }}


